### ISSUE TITLE
CLI command: "si instance input <instance-id>" doesn't read data from stdin

### ISSUE THREAD

**Issue by a-tylenda** [scramjetorg/transform-hub#165]
**Describe the bug**
CLI command `si instance input -h` says:
```
Usage: si instance input [options] <id> [<file>]

send file to input, if file not given the data will be read from stdin

Options:
  -t, --content-type <value>  Content-Type (default: "text/plain")
  -h, --help                  display help for command
```
When I tried to send some data to my running sequence with this command: `$ si instance input 7a1ffd59-9d1a-4e8f-a246-020124803931` it returned an error:
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:119:11)
    at resolve (node:path:1098:7)
    at getReadStreamFromFile (/home/atylenda/.nvm/versions/node/v16.6.1/lib/node_modules/@scramjet/cli/lib/common.js:84:49)
    at Command.<anonymous> (/home/atylenda/.nvm/versions/node/v16.6.1/lib/node_modules/@scramjet/cli/lib/commands/instance.js:63:119)
    at Command.listener [as _actionHandler] (/home/atylenda/.nvm/versions/node/v16.6.1/lib/node_modules/@scramjet/cli/node_modules/commander/lib/command.js:488:17)
    at /home/atylenda/.nvm/versions/node/v16.6.1/lib/node_modules/@scramjet/cli/node_modules/commander/lib/command.js:1227:65
    at Command._chainOrCall (/home/atylenda/.nvm/versions/node/v16.6.1/lib/node_modules/@scramjet/cli/node_modules/commander/lib/command.js:1144:12)
    at Command._parseCommand (/home/atylenda/.nvm/versions/node/v16.6.1/lib/node_modules/@scramjet/cli/node_modules/commander/lib/command.js:1227:27)
    at Command._dispatchSubcommand (/home/atylenda/.nvm/versions/node/v16.6.1/lib/node_modules/@scramjet/cli/node_modules/commander/lib/command.js:1050:25)
```
I also tried this way: `si instance input 7a1ffd59-9d1a-4e8f-a246-020124803931 John`, also didn't work out and returned an error:
```
Error: File "John" not found.
    at /home/atylenda/.nvm/versions/node/v16.6.1/lib/node_modules/@scramjet/cli/lib/common.js:86:15
    at async Command.<anonymous> (/home/atylenda/.nvm/versions/node/v16.6.1/lib/node_modules/@scramjet/cli/lib/commands/instance.js:63:78)
```

It is worth adding that when I give a file as data to send to input the application works just fine: `si inst input 7a1ffd59-9d1a-4e8f-a246-020124803931 name.txt `
```
Request ok: http://127.0.0.1:8000/api/v1/instance/7a1ffd59-9d1a-4e8f-a246-020124803931/input status: 200 OK
```

```
si inst output 7a1ffd59-9d1a-4e8f-a246-020124803931
Request ok: http://127.0.0.1:8000/api/v1/instance/7a1ffd59-9d1a-4e8f-a246-020124803931/output status: 200 OK
Hello John
```

**Steps to Reproduce**
1. git clone git@github.com:scramjetorg/scramjet-cloud-docs.git
2. cd scramjet-cloud-docs/sample/hello
3. Open two terminals and run the following commands:

**The first terminal:**
```bash
# start sth
scramjet-transform-hub
```

**The second terminal**
```bash
# go to 'hello' directory
cd samples/hello

# install dependencies
npm install

# make a compressed package with sequence
si pack . -o hello.tar.gz

# send sequence to transform hub, this will output Sequence ID
si seq send hello.tar.gz

# start a sequence, this will output Instance ID
si seq start <sequence-id>

# See output of instance process
si inst output <instance-id>

# In another terminal send file to instance input steam
si inst input <instance-id> John
```

**Expected behavior**
If the file is not given in the CLI command, then data should be read from stdin as it is said in 'help':
```
$ si instance input -h
Usage: si instance input [options] <id> [<file>]

send file to input, if file not given the data will be read from stdin

Options:
  -t, --content-type <value>  Content-Type (default: "text/plain")
  -h, --help                  display help for command
```
So after running command: `si instance input 7a1ffd59-9d1a-4e8f-a246-020124803931 John` we should get an output:
```
Hello John
```

For now, only reading from the file works:
![image](https://user-images.githubusercontent.com/61054769/146028997-0c9ae77e-8bce-423b-8150-91ce7a055908.png)

**Version (please complete the following information):**
 - STH version: 0.13.1
 - node version: v16.6.1
 - os: Ubuntu 20.4

**Comment by alicja-gruzdz** [comment]
Fixed in https://github.com/scramjetorg/transform-hub/pull/177
