### ISSUE TITLE
Starting a failed sequence hangs indefinitely.

### ISSUE THREAD

**Issue by MichalCz** [scramjetorg/transform-hub#206]
**Describe the bug**
When a sequence is started, for instance with `si seq start sequenceId` and the sequence exits immediately (throws an error) the CLI process hangs and waits forever.

**Steps to Reproduce**

1. Create a sequence that fails (has an error in syntax)
2. Run: `si seq pack <dir> && si seq send <tgz> && si seq start <id>` - see that the start fails.

***Reproduction repo/branch***

Working on it.

**Expected behavior**

An error should be thrown and exitcode 1 should be sent.

**Version (please complete the following information):**
 - STH version: 0.14.0
 - node version: 16.x
 - os: Ubuntu Server 20.04

**Additional information like logs, screenshots etc.**

```
Starting host on port: 34859
Spawning with command: node ../dist/sth/bin/hub.js -P 34859 --instances-server-port 38877 --no-docker
2022-01-14T23:31:35.944Z log (object:Host) Host main called.
2022-01-14T23:31:35.948Z info (object:SocketServer) Server on: { address: '::', family: 'IPv6', port: 38877 }
2022-01-14T23:31:35.951Z info (object:Host) API listening on: 0.0.0.0:34859
Feature: CLI tests # features/e2e/E2E-010-cli.feature:1

  @ci
  Scenario: E2E-010 TC-022 Check minus replacements # features/e2e/E2E-010-cli.feature:203
    Given host is running
2022-01-14T23:31:35.983Z Starting request to http://localhost:34859/api/v1/load-check
2022-01-14T23:31:36.003Z Request ok: http://localhost:34859/api/v1/load-check status: 200 OK
    When I execute CLI with "pack ../packages/reference-apps/hello-alice-out" arguments
2022-01-14T23:31:36.003Z debug (object:Host) Request date: 2022-01-14T23:31:35.987Z, method: GET, url: /api/v1/load-check, status: 200
Spawning command /usr/bin/env si pack ../packages/reference-apps/hello-alice-out -a http://localhost:34859/api/v1
    And I execute CLI with "seq send -" arguments
Spawning command /usr/bin/env si seq send - -a http://localhost:34859/api/v1
2022-01-14T23:31:40.534Z info (object:Host) New sequence incoming...
2022-01-14T23:31:40.545Z info (object:Host) Sequence identified: {
  type: 'process',
  entrypointPath: 'index',
  version: '0.14.0',
  name: '@scramjet/hello-alice-out',
  id: 'cea7f94e-ed2d-40d3-b153-55401aed5d12',
  sequenceDir: '/home/mczapracki/.scramjet_sequences/cea7f94e-ed2d-40d3-b153-55401aed5d12'
}
2022-01-14T23:31:40.545Z debug (object:Host) Request date: 2022-01-14T23:31:40.535Z, method: POST, url: /api/v1/sequence, status: 202
    And I execute CLI with "seq start -" arguments
Spawning command /usr/bin/env si seq start - -a http://localhost:34859/api/v1
2022-01-14T23:31:42.760Z log (API) POST /api/v1/sequence/cea7f94e-ed2d-40d3-b153-55401aed5d12/start
2022-01-14T23:31:42.768Z log (object:LoadCheck) {
  avgLoad: 0.2,
  currentLoad: 33.34974157026828,
  memFree: 5851877376,
  memUsed: 7627407360,
  fsSize: [
    {
      fs: '/dev/sda1',
      type: 'ext4',
      size: 41651752960,
      used: 22517084160,
      available: 19117891584,
      use: 54.08,
      mount: '/'
    },
    {
      fs: '/dev/sda15',
      type: 'vfat',
      size: 109422592,
      used: 6871040,
      available: 102552576,
      use: 6.28,
      mount: '/boot/efi'
    }
  ]
}
2022-01-14T23:31:42.768Z log (object:LoadCheck) { cpu: true, mem: true, dsk: true }
2022-01-14T23:31:42.768Z info (object:Host) Starting sequence cea7f94e-ed2d-40d3-b153-55401aed5d12
2022-01-14T23:31:42.770Z log (object:Host) New CSIController created:  62c75918-8988-427a-a6a3-3e6f5f1761cb
2022-01-14T23:31:42.770Z log (object:CSIController:62c75918-8988-427a-a6a3-3e6f5f1761cb) Streams hooked and routed.
2022-01-14T23:31:42.770Z info (object:ProcessInstanceAdapter) Instance preparation done.
2022-01-14T23:31:42.770Z log (object:ProcessInstanceAdapter) Starting Runner... cea7f94e-ed2d-40d3-b153-55401aed5d12
2022-01-14T23:31:42.770Z log (object:ProcessInstanceAdapter) Spawning Runner process with command [
  '/home/mczapracki/.nvm/versions/node/v16.13.2/bin/node',
  '/home/mczapracki/src/scramjetorg/transform-hub/dist/runner/bin/start-runner.js'
] and envs:  {
  DEVELOPMENT: undefined,
  PRODUCTION: undefined,
  SEQUENCE_PATH: '/home/mczapracki/.scramjet_sequences/cea7f94e-ed2d-40d3-b153-55401aed5d12/index',
  INSTANCES_SERVER_PORT: 38877,
  INSTANCE_ID: '62c75918-8988-427a-a6a3-3e6f5f1761cb'
}
2022-01-14T23:31:42.774Z log (object:ProcessInstanceAdapter) Runner process is running (638389).
2022-01-14T23:31:42.774Z info (object:CSIController:62c75918-8988-427a-a6a3-3e6f5f1761cb) Sequence initialized.
2022-01-14T23:31:42.855Z log (object:ProcessInstanceAdapter) Process exited.
2022-01-14T23:31:42.855Z debug (object:ProcessInstanceAdapter) Process returned non-zero status code 1
2022-01-14T23:31:42.855Z log (object:CSIController:62c75918-8988-427a-a6a3-3e6f5f1761cb) Sequence finished with status: 1
    ✖ failed
      Error: function timed out, ensure the promise resolves within 30000 milliseconds
          at Timeout._onTimeout (/home/mczapracki/src/scramjetorg/transform-hub/node_modules/@cucumber/cucumber/src/user_code_runner.ts:80:18)
          at listOnTimeout (node:internal/timers:557:17)
          at processTimers (node:internal/timers:500:7)
    Then I get the last sequence id from config
    - skipped
    And I get instance info
    - skipped
    And I execute CLI with "inst kill -" arguments
    - skipped
    And I execute CLI with "seq del -" arguments
    - skipped
    And host is still running
    - skipped

Failures:

1) Scenario: E2E-010 TC-022 Check minus replacements # features/e2e/E2E-010-cli.feature:203
   ✔ Before # step-definitions/e2e/host-steps.ts:144
   ✔ Given host is running # step-definitions/e2e/host-steps.ts:192
   ✔ When I execute CLI with "pack ../packages/reference-apps/hello-alice-out" arguments # step-definitions/e2e/cli.ts:38
   ✔ And I execute CLI with "seq send -" arguments # step-definitions/e2e/cli.ts:38
   ✖ And I execute CLI with "seq start -" arguments # step-definitions/e2e/cli.ts:38
       Error: function timed out, ensure the promise resolves within 30000 milliseconds
           at Timeout._onTimeout (/home/mczapracki/src/scramjetorg/transform-hub/node_modules/@cucumber/cucumber/src/user_code_runner.ts:80:18)
           at listOnTimeout (node:internal/timers:557:17)
           at processTimers (node:internal/timers:500:7)
   - Then I get the last sequence id from config # step-definitions/e2e/cli.ts:135
   - And I get instance info # step-definitions/e2e/cli.ts:239
   - And I execute CLI with "inst kill -" arguments # step-definitions/e2e/cli.ts:38
   - And I execute CLI with "seq del -" arguments # step-definitions/e2e/cli.ts:38
   - And host is still running # step-definitions/e2e/host-steps.ts:202

1 scenario (1 failed)
9 steps (1 failed, 5 skipped, 3 passed)
0m34.909s (executing steps: 0m34.619s)
host process exited with code:  null  and signal:  SIGTERM
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by patuwwy** [comment]
Working on it. 
Reproduced with sending packed sequence without index.js 
Running sequence throwing an error immediately is working as expected.

**Comment by patuwwy** [comment]
Completing the process of running the sequence requires connecting the Runner to the Host. In the current implementation of running Runner, we check a few conditions needed to run the instance - including whether the sequence file specified in "main" in package.json exists. If, during verification, an unsatisfied Runner condition is encountered, it will end with no connection to the Host.

In this case, the process of starting the instance will be waiting.

**Comment by patuwwy** [comment]
> Running sequence throwing an error immediately is working as expected.

I mean, it returns `HTTP 200` what means sequence has been started. As discussed with @ErykSol it probably should be `202`
