### ISSUE TITLE
[CLI]  connect to endpoint with self signed certs

### ISSUE THREAD

**Issue by daro1337** [scramjetorg/transform-hub#411]
**Feature description**

We should add ability via some argument to connect to endpoint with self signed certs e.g for development purposes.
Some argument like `-k` / `--insecure` in curl  will be nice to have

Current error:
```
 si config set middlewareApiUrl 'https://self-signed.badssl.com/'

 si seq list
Request failed with code "DEPTH_ZERO_SELF_SIGNED_CERT" status: undefined
ClientError: Response code is "DEPTH_ZERO_SELF_SIGNED_CERT"
    at Function.from (/home/daro/.nvm/versions/node/v16.13.2/lib/node_modules/@scramjet/cli/node_modules/@scramjet/client-utils/client-error.js:49:24)
    at ClientUtils.safeRequest (/home/daro/.nvm/versions/node/v16.13.2/lib/node_modules/@scramjet/cli/node_modules/@scramjet/client-utils/client-utils.js:57:46)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async displayEntity (/home/daro/.nvm/versions/node/v16.13.2/lib/node_modules/@scramjet/cli/lib/output.js:33:17) {
  code: 'UNKNOWN_ERROR',
  reason: QueryError: Failed to request 'https://self-signed.badssl.com//api/v1/space/org-5cfb82c4-31d4-4f10-93f6-b441858f0396-manager/api/v1/sth/sth-6cd78f999b-ntdtw/api/v1/sequences' with code DEPTH_ZERO_SELF_SIGNED_CERT.
      at /home/daro/.nvm/versions/node/v16.13.2/lib/node_modules/@scramjet/cli/node_modules/@scramjet/client-utils/client-utils.js:43:23
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async ClientUtils.safeRequest (/home/daro/.nvm/versions/node/v16.13.2/lib/node_modules/@scramjet/cli/node_modules/@scramjet/client-utils/client-utils.js:25:30)
      at async displayEntity (/home/daro/.nvm/versions/node/v16.13.2/lib/node_modules/@scramjet/cli/lib/output.js:33:17) {
    url: 'https://self-signed.badssl.com//api/v1/space/org-5cfb82c4-31d4-4f10-93f6-b441858f0396-manager/api/v1/sth/sth-6cd78f999b-ntdtw/api/v1/sequences',
    code: 'DEPTH_ZERO_SELF_SIGNED_CERT',
    body: undefined,
    response: undefined
  },
  body: undefined,
  status: 'DEPTH_ZERO_SELF_SIGNED_CERT'
}
```

**Comment by daro1337** [comment]
This workaround is not recommended and safe
```
NODE_TLS_REJECT_UNAUTHORIZED=0
```
Anyway it will be nice to have `--insecure` flag

**Comment by alicja-gruzdz** [comment]
After consulting with @daro1337: not a priority, he can use a workaround, but we may need it for encrypted STH<->MM connection.
