### ISSUE TITLE
`si` broken on mac

### ISSUE THREAD

**Issue by patuwwy** [scramjetorg/transform-hub#497]
```
Patu@air reference-apps % si
node:internal/fs/utils:345
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/proc/self/stat'
    at Object.openSync (node:fs:590:3)
    at readFileSync (node:fs:458:35)
    at sessionId (/Users/Patu/github/transform-hub/dist/cli/utils/sessionId.js:5:47)
    at Object.<anonymous> (/Users/Patu/github/transform-hub/dist/cli/lib/paths.js:14:92)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/proc/self/stat'
}

Node.js v18.1.0
```

**Version (please complete the following information):**
 - STH version: 0.22
 - node version: 18
 - os: macos big sur 11.06 

**Additional information like logs, screenshots etc.**

**Comment by patuwwy** [comment]
#524

**Comment by MichalCz** [comment]
![Zrzut ekranu 2022-08-25 o 22.11.16.png](https://user-images.githubusercontent.com/1292420/186786617-d87ed080-3006-4f00-b41c-b9934773614e.png)

Now not only si but also STH work on Mac quite well. :)
