### ISSUE TITLE
Setting max memory from command line fails

### ISSUE THREAD

**Issue by mcdominik** [scramjetorg/transform-hub#805]
**Describe the bug**
I'm trying to run sth on raspberry pi with `--safe-operation-limit` parameter and it fails

**Steps to Reproduce**
```
pi@raspberrypi:~ $ sth --no-docker --safe-operation-limit 128
Error: Invalid load-check configuration
    at new LoadCheck (/usr/lib/node_modules/@scramjet/sth/node_modules/@scramjet/load-check/load-check.js:16:19)
    at new Host (/usr/lib/node_modules/@scramjet/sth/node_modules/@scramjet/host/lib/host.js:64:26)
    at createHost (/usr/lib/node_modules/@scramjet/sth/node_modules/@scramjet/host/lib/start-host.js:10:18)
    at Object.startHost (/usr/lib/node_modules/@scramjet/sth/node_modules/@scramjet/host/lib/start-host.js:14:18)
    at /usr/lib/node_modules/@scramjet/sth/bin/hub.js:130:38
    at Object.<anonymous> (/usr/lib/node_modules/@scramjet/sth/bin/hub.js:154:3)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
```

**Expected behavior**
start without crash

**Workaround**
rpi_config.json:
```
{
"runtimeAdapter": "process",
"safeOperationLimit": 128,
"instanceRequirements": { "freeMem": 64 }
}
```

`sth --config /path/to/config/rpi_config.json`

**Version:**
 - STH version: 0.32.1
 - node version: 16.X
 - os: raspberry pi os 64bit, 5.15 kernel

**Comment by ErykSol** [comment]
Fixed in https://github.com/scramjetorg/transform-hub/pull/817
